USE QuanLyGiaoVu;

-------------------------------- Bai Tap 2 ----------------------------------
-- Phần I bài tập QuanLyGiaoVu câu 9, 10, và từ câu 15 đến câu 24

---------------------------------- Cau 9 ------------------------------------
-- Lớp trưởng của một lớp phải là học viên của lớp đó.

----------------------- Bảng tầm ảnh hưởng ----------------------------
--> Bối cảnh: HOCVIEN, LOP
--> Bảng tầm ảnh hưởng:
--  LOP: INSERT, UPDATE(TRGLOP)

-- LOP: INSERT
CREATE TRIGGER TRGLOP_LOP_INSERT
ON LOP
FOR INSERT
AS 
BEGIN
	-- Khởi tạo
	DECLARE @TRGLOP CHAR(5), @MALOP CHAR(3)

	-- Gán giá trị
	SELECT @TRGLOP = TRGLOP
	FROM inserted

	SELECT @MALOP = MALOP
	FROM inserted

	-- Kiểm tra điều kiện
	IF NOT EXISTS(
		SELECT *
		FROM HOCVIEN HV
		WHERE HV.MAHV = @TRGLOP AND HV.MALOP = @MALOP
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: LOP TRUONG PHAI LA HOC VIEN CUA LOP --> INSERT KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: LOP TRUONG PHAI LA HOC VIEN CUA LOP --> INSERT THANH CONG';
	END
END

-- Test Trigger
SELECT *
FROM LOP
JOIN HOCVIEN ON HOCVIEN.MAHV = LOP.TRGLOP;

-- Không hợp lệ
INSERT INTO LOP(MALOP, TENLOP, TRGLOP, SISO, MAGVCN)
VALUES ('K14', 'Lop 4 khoa 1', 'K1105', 11, 'GV01');

-- LOP: UPDATE(TRGLOP)
CREATE TRIGGER TRGLOP_LOP_UPDATE
ON LOP
FOR UPDATE
AS 
BEGIN
	-- Khởi tạo
	DECLARE @TRGLOP CHAR(5), @MALOP CHAR(3)

	-- Gán giá trị
	SELECT @TRGLOP = TRGLOP
	FROM inserted

	SELECT @MALOP = MALOP
	FROM inserted

	-- Kiểm tra điều kiện
	IF NOT EXISTS(
		SELECT *
		FROM HOCVIEN HV
		WHERE HV.MAHV = @TRGLOP AND HV.MALOP = @MALOP
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: LOP TRUONG PHAI LA HOC VIEN CUA LOP --> UPDATE KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: LOP TRUONG PHAI LA HOC VIEN CUA LOP --> UPDATE THANH CONG';
	END
END

-- Test trigger
SELECT *
FROM LOP
JOIN HOCVIEN ON HOCVIEN.MAHV = LOP.TRGLOP;

-- Không hợp lệ
UPDATE LOP 
SET TRGLOP = 'K1201'
WHERE MALOP = 'K11';

-- Hợp lệ
UPDATE LOP 
SET TRGLOP = 'K1101'
WHERE MALOP = 'K11';

----------------------------- Cau 10 ------------------------------
-- Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.

----------------------- Bảng tầm ảnh hưởng ----------------------------
--> Bối cảnh: KHOA, GIAOVIEN
--> Bảng tầm ảnh hưởng:
--  KHOA: INSERT, UPDATE(TRGKHOA)
--  GIAOVIEN: UPDATE(MAKHOA)

-- KHOA: INSERT
CREATE TRIGGER TRGKHOA_KHOA_INSERT
ON KHOA
FOR INSERT
AS 
BEGIN
	-- Khởi tạo
	DECLARE @MAKHOA VARCHAR(4), @TRGKHOA CHAR(4)

	-- Gán giá trị
	SELECT @MAKHOA = MAKHOA
	FROM inserted

	SELECT @TRGKHOA = TRGKHOA
	FROM inserted

	-- Kiểm tra điều kiện
	IF NOT EXISTS (
		SELECT *
		FROM GIAOVIEN GV
		WHERE (GV.HOCVI = 'TS' OR GV.HOCVI = 'PTS')
			AND GV.MAGV = @TRGKHOA 
			AND GV.MAKHOA = @MAKHOA
	)
	BEGIN 
		PRINT 'KHONG THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> THEM KHOA KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END 
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> THEM KHOA THANH CONG';
	END
END

-- Test trigger
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP, TRGKHOA)
VALUES ('TTNT', 'Tri tue nhan tao', '2005-06-07 00:00:00', 'GV05');

-- KHOA: UPDATE(TRGKHOA)
CREATE TRIGGER TRGKHOA_KHOA_UPDATE
ON KHOA
FOR UPDATE
AS 
BEGIN
	-- Khởi tạo
	DECLARE @MAKHOA VARCHAR(4), @TRGKHOA CHAR(4)

	-- Gán giá trị
	SELECT @MAKHOA = MAKHOA
	FROM inserted

	SELECT @TRGKHOA = TRGKHOA
	FROM inserted

	-- Kiểm tra điều kiện
	IF NOT EXISTS (
		SELECT *
		FROM GIAOVIEN GV
		WHERE (GV.HOCVI = 'TS' OR GV.HOCVI = 'PTS')
			AND GV.MAGV = @TRGKHOA 
			AND GV.MAKHOA = @MAKHOA
	)
	BEGIN 
		PRINT 'KHONG THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> UPDATE TRGKHOA KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END 
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> UPDATE TRGKHOA THANH CONG';
	END
END

-- Test trigger

-- Không thành công
UPDATE KHOA 
SET TRGKHOA = 'GV09'
WHERE MAKHOA = 'CNPM';

-- Thành công
UPDATE KHOA 
SET TRGKHOA = 'GV06'
WHERE MAKHOA = 'KHMT';

-- GIAOVIEN: UPDATE(MAKHOA)
CREATE TRIGGER TRGKHOA_GIAOVIEN_UPDATE
ON GIAOVIEN
FOR UPDATE
AS 
BEGIN 
	-- Khởi tạo
	DECLARE @MAGV CHAR(4), @MAKHOA VARCHAR(4)

	-- Gán giá trị
	SELECT @MAGV = MAGV
	FROM inserted

	SELECT @MAKHOA = MAKHOA
	FROM inserted

	-- Kiểm tra điều kiện
	IF NOT EXISTS (
		SELECT *
		FROM KHOA AS K
		JOIN GIAOVIEN AS GV
		ON GV.MAGV = K.TRGKHOA 
			AND K.MAKHOA = GV.MAKHOA
		WHERE GV.MAGV = @MAGV AND K.MAKHOA = @MAKHOA
			AND GV.HOCVI IN ('TS', 'PTS')
	)
	BEGIN 
		PRINT 'KHONG THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> UPDATE MAKHOA KHONG THANH CONG'
		ROLLBACK TRANSACTION;
	END
	ELSE
	BEGIN
		PRINT 'THOA DIEU KIEN: TRUONG KHOA LA GIAO VIEN THUOC KHOA CO HOC VI TS HOAC PTS --> UPDATE MAKHOA THANH CONG'
	END
END

DROP TRIGGER TRGKHOA_GIAOVIEN_UPDATE;

-- Test trigger
UPDATE GIAOVIEN
SET MAKHOA = 'CNPM'
WHERE MAGV = 'GV03';

UPDATE GIAOVIEN 
SET MAKHOA = 'CNPM'
WHERE MAGV = 'GV08';

----------------------------------------- Cau 15 -------------------------------------
-- Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.

----------------------- Bảng tầm ảnh hưởng ----------------------------
--> Bối cảnh: HOCVIEN, GIANGDAY, KETQUATHI
--> Bảng tầm ảnh hưởng:
--  GIANGDAY: UPDATE(DENNGAY)
--  KETQUATHI: INSERT, UPDATE(NGTHI)

-- GIANGDAY: UPDATE(DENNGAY)
CREATE TRIGGER NGTHI_DENNGAY_GIANGDAY_UPDATE
ON GIANGDAY
FOR UPDATE
AS
BEGIN
	-- Khởi tạo
	DECLARE @DENNGAY SMALLDATETIME, @MALOP CHAR(3), @MAMH VARCHAR(10)

	-- Gán giá trị
	SELECT @DENNGAY = DENNGAY 
	FROM inserted

	SELECT @MALOP = MALOP 
	FROM inserted

	SELECT @MAMH = MAMH
	FROM inserted

	-- Kiểm tra điều kiện
	IF EXISTS (
		SELECT *
		FROM HOCVIEN AS HV
		JOIN KETQUATHI AS KQ
		ON HV.MAHV = KQ.MAHV 
		WHERE HV.MALOP = @MALOP
			AND @DENNGAY >= KQ.NGTHI
			AND @MAMH = KQ.MAMH
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> UPDATE DENNGAY KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> UPDATE DENNGAY THANH CONG';
	END
END

DROP TRIGGER NGTHI_DENNGAY_GIANGDAY_UPDATE;

-- Test trigger

-- KHONG THANH CONG
UPDATE GIANGDAY
SET DENNGAY = '2006-07-20 00:00:00'
WHERE MALOP = 'K11' AND MAMH = 'CSDL';

-- THANH CONG
UPDATE GIANGDAY
SET DENNGAY = '2006-07-18 00:00:00'
WHERE MALOP = 'K11' AND MAMH = 'CSDL';



-- KETQUATHI: INSERT
CREATE TRIGGER NGTHI_DENNGAY_KETQUATHI_INSERT
ON KETQUATHI
FOR INSERT
AS 
BEGIN
	-- Khởi tạo
	DECLARE @MAHV CHAR(5), @MAMH VARCHAR(10), @NGTHI SMALLDATETIME

	-- Gán giá trị
	SELECT @MAHV = MAHV
	FROM inserted

	SELECT @MAMH = MAMH
	FROM inserted

	SELECT @NGTHI = NGTHI
	FROM inserted

	-- Kiểm tra điều kiện
	IF EXISTS (
		SELECT * 
		FROM HOCVIEN AS HV
		JOIN GIANGDAY AS GD
		ON HV.MALOP = GD.MALOP
		WHERE @MAHV = HV.MAHV AND GD.MAMH = @MAMH
			AND @NGTHI <= GD.DENNGAY
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> INSERT KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> INSERT KETQUATHI THANH CONG';
	END
END

-- Test trigger

-- Khong thanh cong
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1204', 'THDC', 2, '2006-05-10 00:00:00', 10.0);

-- Thanh cong
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1204', 'THDC', 2, '2006-05-15 00:00:00', 10.0);

-- KETQUATHI: UPDATE(NGTHI)
CREATE TRIGGER NGTHI_DENNGAY_KETQUATHI_UPDATE
ON KETQUATHI
FOR UPDATE
AS 
BEGIN
	-- Khởi tạo
	DECLARE @MAHV CHAR(5), @MAMH VARCHAR(10), @NGTHI SMALLDATETIME

	-- Gán giá trị
	SELECT @MAHV = MAHV
	FROM inserted

	SELECT @MAMH = MAMH
	FROM inserted

	SELECT @NGTHI = NGTHI
	FROM inserted

	-- Kiểm tra điều kiện
	IF EXISTS (
		SELECT * 
		FROM HOCVIEN AS HV
		JOIN GIANGDAY AS GD
		ON HV.MALOP = GD.MALOP
		WHERE @MAHV = HV.MAHV AND GD.MAMH = @MAMH
			AND @NGTHI <= GD.DENNGAY
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> UPDATE NGTHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI MOT MON KHI DA HOC XONG MON DO --> UPDATE NGTHI THANH CONG';
	END
END

-- Test trigger

-- KHONG THANH CONG
UPDATE KETQUATHI
SET NGTHI = '2006-05-10 00:00:00'
WHERE MAMH = 'THDC' AND MAHV = 'K1204' AND LANTHI = 1;

-- THANH CONG
UPDATE KETQUATHI
SET NGTHI = '2006-05-22 00:00:00'
WHERE MAMH = 'THDC' AND MAHV = 'K1204' AND LANTHI = 1;


-------------------------------- Cau 16 --------------------------------
-- Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.

----------------------- Bảng tầm ảnh hưởng ----------------------------
--> Bối cảnh: GIANGDAY
--> Bảng tầm ảnh hưởng:
--  GIANGDAY: INSERT, UPDATE(NAM, HOCKY)

CREATE TRIGGER MAX_SUBJECT_GIANGDAY_INSERT
ON GIANGDAY
FOR INSERT
AS
BEGIN
	-- Khởi tạo
	DECLARE @NAM SMALLINT, @HOCKY TINYINT, @MALOP CHAR(3), @MAMH VARCHAR(10)

	-- Gán giá trị
	SELECT @NAM = NAM
	FROM inserted

	SELECT @HOCKY = HOCKY
	FROM inserted

	SELECT @MALOP = MALOP 
	FROM inserted

	SELECT @MAMH = MAMH
	FROM inserted

	-- Kiểm tra điều kiện
	IF (
		SELECT COUNT(DISTINCT MAMH)
		FROM GIANGDAY AS GD
		WHERE @NAM = GD.NAM AND @HOCKY = GD.HOCKY AND @MALOP = GD.MALOP
	) >= 3
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: MOI HOC KY CUA MOT NAM, MOT LOP CHI DUOC HOC TOI DA 3 MON --> INSERT GIANGDAY KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: MOI HOC KY CUA MOT NAM, MOT LOP CHI DUOC HOC TOI DA 3 MON --> INSERT GIANGDAY THANH CONG';
	END
END

-- Test trigger
UPDATE GIANGDAY
SET HOCKY = 1
WHERE MALOP = 'K12' AND MAMH = 'CSDL';

-- KHONG THANH CONG
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
VALUES ('K12', 'DHMT', 'GV02', 1, 2006, '2006-01-09 00:00:00', '2006-05-17 00:00:00');

-- GIANGDAY: UPDATE(NAM, HOCKY)
CREATE TRIGGER MAX_SUBJECT_GIANGDAY_UPDATE
ON GIANGDAY
FOR UPDATE
AS
BEGIN
	-- Khởi tạo
	DECLARE @NAM SMALLINT, @HOCKY TINYINT, @MALOP CHAR(3), @MAMH VARCHAR(10)

	-- Gán giá trị
	SELECT @NAM = NAM
	FROM inserted

	SELECT @HOCKY = HOCKY
	FROM inserted

	SELECT @MALOP = MALOP 
	FROM inserted

	SELECT @MAMH = MAMH
	FROM inserted

	-- Kiểm tra điều kiện
	IF (
		SELECT COUNT(DISTINCT MAMH)
		FROM GIANGDAY AS GD
		WHERE @NAM = GD.NAM AND @HOCKY = GD.HOCKY AND @MALOP = GD.MALOP
	) >= 3
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: MOI HOC KY CUA MOT NAM, MOT LOP CHI DUOC HOC TOI DA 3 MON --> UPDATE NAM/HOC KY KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: MOI HOC KY CUA MOT NAM, MOT LOP CHI DUOC HOC TOI DA 3 MON --> UPDATE NAM/HOC KY THANH CONG';
	END
END

DROP TRIGGER MAX_SUBJECT_GIANGDAY_UPDATE;

-- Test trigger

-- UPDATE NAM --> KHONG THANH CONG
UPDATE GIANGDAY
SET NAM = 2006
WHERE MALOP = 'K12' AND MAMH = 'HDH';

-- UPDATE HOCKY --> KHONG THANH CONG
UPDATE GIANGDAY
SET HOCKY = 1
WHERE MALOP = 'K12' AND MAMH = 'CSDL';

---------------------------- Cau 17 ----------------------------
-- Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó. 

--  Bối cảnh: LOP, HOCVIEN
--  Bảng tầm ảnh hưởng:
--> HOCVIEN: INSERT, DELETE


-- HOCVIEN: INSERT
CREATE TRIGGER SISO_HOCVIEN_INSERT
ON HOCVIEN
FOR INSERT
AS
BEGIN
	-- Kiểm tra điều kiện
	IF EXISTS (
		SELECT *
		FROM (
			SELECT L.MALOP, L.SISO, COUNT(HV.MAHV) + COUNT(inserted.MAHV) AS [Tổng Số Học Viên]
			FROM HOCVIEN AS HV
			JOIN LOP AS L
			ON HV.MALOP = L.MALOP
			JOIN inserted 
			ON inserted.MALOP = L.MALOP
			GROUP BY L.MALOP, L.SISO
			HAVING COUNT(HV.MAHV) + COUNT(inserted.MAHV) > L.SISO
		) AS CheckCondition
	)
	BEGIN
		PRINT 'LOP DA DU HOC VIEN --> INSERT HOCVIEN KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'LOP CHUA DU HOC VIEN --> INSERT HOCVIEN THANH CONG';
	END
END

DROP TRIGGER SISO_HOCVIEN_INSERT;

-- Test trigger
INSERT INTO HOCVIEN (MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP, GHICHU, DIEMTB)
VALUES ('K1111', 'Nguyen Van', 'An', '1986-12-25 00:00:00', 'Nam', 'Ha Noi', 'K11', NULL, 9.0);

DELETE FROM HOCVIEN
WHERE MAHV = 'K1112';

-- HOCVIEN: DELETE
CREATE TRIGGER SISO_HOCVIEN_DELETE
ON HOCVIEN
FOR DELETE
AS 
BEGIN
	-- Xóa học viên ra khỏi lớp
	UPDATE LOP
	SET SISO = SISO - (
		SELECT COUNT(*)
		FROM deleted
		WHERE deleted.MALOP = LOP.MALOP
	)
	WHERE MALOP IN (
		SELECT MALOP
		FROM deleted
	)

	-- Kiểm tra điều kiện
	IF EXISTS (
		SELECT *
		FROM LOP 
		WHERE SISO < 0
			AND MALOP IN (
				SELECT MALOP
				FROM deleted
			)
	)
	BEGIN
		PRINT 'LOP KHONG CO HOC VIEN --> DELETE HOCVIEN KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END 
	ELSE 
	BEGIN	
		PRINT 'DELETE HOCVIEN THANH CONG';
	END
END

DROP TRIGGER SISO_HOCVIEN_DELETE;

-- Test trigger
DELETE FROM HOCVIEN 
WHERE MAHV = 'K1110';

-------------------------------- Cau 19 ------------------------------
-- Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau. 

--   Bối cảnh: GIAOVIEN 
--   Bảng tầm ảnh hưởng:
-->  GIAOVIEN: INSERT, UPDATE(HOCVI, HOCHAM, HESOLUONG)

--  GIAOVIEN: INSERT
CREATE TRIGGER LUONG_GIAOVIEN_INSERT
ON GIAOVIEN 
FOR INSERT
AS
BEGIN
	IF EXISTS (
		SELECT GV.HOCVI, GV.HOCHAM, GV.HESO
		FROM GIAOVIEN AS GV
		JOIN inserted
		ON inserted.HOCVI = GV.HOCVI 
			AND inserted.HOCHAM = GV.HOCHAM
			AND inserted.HESO = GV.HESO
		GROUP BY GV.HOCVI, GV.HOCHAM, GV.HESO
		HAVING COUNT(DISTINCT GV.MUCLUONG) > 1
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: GIANG VIEN CO CUNG HOC VI, HOC HAM, HE SO LUONG CO MUC LUONG BANG NHAU --> INSERT GIAOVIEN KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: GIANG VIEN CO CUNG HOC VI, HOC HAM, HE SO LUONG CO MUC LUONG BANG NHAU --> INSERT GIAOVIEN THANH CONG';
	END
END

DROP TRIGGER LUONG_GIAOVIEN_INSERT;

-- Test trigger

-- KHONG HOP LE
INSERT INTO GIAOVIEN (MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA)
VALUES ('GV16', 'Ho Thanh AN', 'PTS', 'GS', 'Nam', '1950-05-02 00:00:00', '2004-01-11 00:00:00', 6.20, 2150000.00, 'KHMT');

-- THANH CONG
INSERT INTO GIAOVIEN (MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA)
VALUES ('GV16', 'Ho Thanh AN', 'PTS', 'GS', 'Nam', '1950-05-02 00:00:00', '2004-01-11 00:00:00', 6.20, 2250000.00, 'KHMT');


-- GIAOVIEN: UPDATE(HOCVI, HOCHAM, HESOLUONG)
CREATE TRIGGER LUONG_GIAOVIEN_UPDATE
ON GIAOVIEN
AFTER UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted AS I
        JOIN deleted AS D
        ON I.MAGV = D.MAGV
        WHERE 
            I.HOCVI <> D.HOCVI OR
            I.HOCHAM <> D.HOCHAM OR
            I.HESO <> D.HESO
    )
    BEGIN
        IF EXISTS (
            SELECT I.HOCVI, I.HOCHAM, I.HESO
            FROM inserted AS I
            JOIN GIAOVIEN AS GV
                ON I.HOCVI = GV.HOCVI
                AND I.HOCHAM = GV.HOCHAM
                AND I.HESO = GV.HESO
            GROUP BY I.HOCVI, I.HOCHAM, I.HESO
            HAVING COUNT(DISTINCT GV.MUCLUONG) > 1
        )
        BEGIN
            PRINT 'KHONG THOA DIEU KIEN: GIANG VIEN CO CUNG HOC VI, HOC HAM, HE SO LUONG CO MUC LUONG KHAC NHAU --> UPDATE KHONG THANH CONG';
            ROLLBACK TRANSACTION;
        END
        ELSE
        BEGIN
            PRINT 'THOA DIEU KIEN: GIANG VIEN CO CUNG HOC VI, HOC HAM, HE SO LUONG CO MUC LUONG BANG NHAU --> UPDATE THANH CONG';
        END
    END
END


DROP TRIGGER LUONG_GIAOVIEN_UPDATE;

-- Test trigger
UPDATE GIAOVIEN
SET HOCVI = 'CN'
WHERE MAGV = 'GV09';

UPDATE GIAOVIEN
SET HOCHAM = NULL
WHERE MAGV = 'GV11';

UPDATE GIAOVIEN
SET HESO = 3.0
WHERE MAGV = 'GV09';

------------------------------------ Cau 20 ----------------------------------
-- Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5. 

-- Bối cảnh: KETQUATHI
-- KETQUATHI: INSERT, DELETE, UPDATE(DIEM)


-- KETQUATHI: INSERT
CREATE TRIGGER LANTHI_KETQUATHI_INSERT
ON KETQUATHI
AFTER INSERT
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted
		WHERE inserted.LANTHI > 1 -- Thi lại
			AND NOT EXISTS ( -- Không tồn tại lần thi trước đó dưới 5
				SELECT *
				FROM KETQUATHI AS KQ
				WHERE KQ.MAHV = inserted.MAHV
					AND KQ.MAMH = inserted.MAMH
					AND KQ.LANTHI = inserted.LANTHI - 1
					AND KQ.DIEM < 5
			)
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> INSERT KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOCVIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> INSERT KETQUATHI THANH CONG';
	END
END

-- Test trigger

-- KHONG THANH CONG
INSERT INTO KETQUATHI (MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1102', 'CTRR', 2, '2006-05-16 00:00:00', 7.00);

-- THANH CONG
INSERT INTO KETQUATHI (MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1202', 'THDC', 3, '2006-08-1 00:00:00', 7.00);

-- KETQUATHI: DELETE
CREATE TRIGGER LANTHI_KETQUATHI_DELETE 
ON KETQUATHI
FOR DELETE
AS 
BEGIN
	IF EXISTS (
		SELECT *
		FROM deleted
		WHERE deleted.LANTHI >= 1 -- Chỉ xét với có thi lại
			AND EXISTS ( -- Tồn tại lần thi lại của lần thi bị xóa
				SELECT *
				FROM KETQUATHI AS KQ
				WHERE KQ.MAHV = deleted.MAHV
					AND KQ.MAMH = deleted.MAMH
					AND KQ.LANTHI = deleted.LANTHI + 1
					AND deleted.DIEM < 5
			)
	) 
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> DELETE KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> DELETE KETQUATHI THANH CONG';
	END
END

DROP TRIGGER  LANTHI_KETQUATHI_DELETE ;

-- Test trigger

-- KHONG THANH CONG
DELETE FROM KETQUATHI
WHERE MAHV = 'K1202' AND MAMH = 'CTRR' AND LANTHI = 2;

-- THANH CONG
DELETE FROM KETQUATHI
WHERE MAHV = 'K1202' AND MAMH = 'CTRR' AND LANTHI = 3;

-- KETQUATHI: UPDATE(DIEM)
CREATE TRIGGER LANTHI_KETQUATHI_UPDATE
ON KETQUATHI
FOR UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted
		JOIN deleted
		ON inserted.MAHV = deleted.MAHV
			AND inserted.MAMH = deleted.MAMH
			AND inserted.LANTHI = deleted.LANTHI
		WHERE inserted.LANTHI >= 1
			AND inserted.DIEM >= 5
			AND EXISTS (
				SELECT *
				FROM KETQUATHI AS KQ
				WHERE KQ.MAHV = inserted.MAHV
					AND KQ.MAMH = inserted.MAMH
					AND deleted.DIEM < 5
					AND deleted.LANTHI + 1 = KQ.LANTHI
			)
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> UPDATE KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DO DUOI 5 --> UPDATE KETQUATHI THANH CONG';
	END
END

DROP TRIGGER LANTHI_KETQUATHI_UPDATE;

-- Test trigger
UPDATE KETQUATHI
SET DIEM = 6.0
WHERE MAHV = 'K1202' AND MAMH = 'THDC' AND LANTHI = 2;

UPDATE KETQUATHI
SET DIEM = 10
WHERE MAHV = 'K1301' AND MAMH = 'CSDL' AND LANTHI = 1;

------------------------------- Cau 21 ------------------------------
-- Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn 
-- học).

-- Bối cảnh: KETQUATHI
-- KETQUATHI: INSERT, UPDATE(NGTHI)

-- KETQUATHI: INSERT
CREATE TRIGGER NGTHI_KETQUATHI_INSERT
ON KETQUATHI
FOR INSERT
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted
		WHERE inserted.LANTHI > 1 -- Thi lại
			AND NOT EXISTS ( -- Không tồn tại ngày thi trước nhỏ hơn ngày thi được thêm
				SELECT *
				FROM KETQUATHI AS KQ
				WHERE KQ.MAHV = inserted.MAHV
					AND KQ.MAMH = inserted.MAMH
					AND KQ.NGTHI < inserted.NGTHI
					AND KQ.LANTHI = inserted.LANTHI - 1
			)
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: NGTHI CUA LAN THI SAU PHAI LON HON NGTHI CUA LAN THI TRUOC --> INSERT KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: NGTHI CUA LAN THI SAU PHAI LON HON NGTHI CUA LAN THI TRUOC --> INSERT KETQUATHI THANH CONG';
	END
END

DROP TRIGGER NGTHI_KETQUATHI_INSERT;

-- Test trigger

-- KHONG THANH CONG
INSERT INTO KETQUATHI (MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1303', 'THDC', 2, '2006-05-16 00:00:00', 7.00);

-- THANH CONG
INSERT INTO KETQUATHI (MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1303', 'THDC', 2, '2006-05-25 00:00:00', 7.00);

-- KETQUATHI: UPDATE(NGTHI)
CREATE TRIGGER NGTHI_KETQUATHI_UPDATE
ON KETQUATHI
FOR UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted
		JOIN deleted
		ON inserted.MAHV = deleted.MAHV
			AND inserted.MAMH = deleted.MAMH
			AND inserted.LANTHI = deleted.LANTHI
		WHERE inserted.LANTHI >= 1
			AND EXISTS (
				SELECT *
				FROM KETQUATHI AS KQ
				WHERE KQ.MAHV = inserted.MAHV
					AND KQ.MAMH = inserted.MAMH
					AND KQ.NGTHI >= inserted.NGTHI
					AND KQ.LANTHI = inserted.LANTHI - 1
					AND KQ.NGTHI < deleted.NGTHI
			)
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: NGTHI CUA LAN THI SAU PHAI LON HON NGTHI CUA LAN THI TRUOC --> UPDATE KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE
	BEGIN	
		PRINT 'THOA DIEU KIEN: NGTHI CUA LAN THI SAU PHAI LON HON NGTHI CUA LAN THI TRUOC --> UPDATE KETQUATHI THANH CONG';
	END
END

DROP TRIGGER NGTHI_KETQUATHI_UPDATE;

-- Test trigger
UPDATE KETQUATHI
SET NGTHI = '2006-07-20 00:00:00'
WHERE MAHV = 'K1303' AND MAMH = 'CTDLGT' AND LANTHI = 2;

----------------------------------- Cau 22 --------------------------------------
-- Học viên chỉ được thi những môn mà lớp của học viên đó đã học xong.

--  Bối cảnh: HOCVIEN, GIANGDAY, KETQUATHI
--  HOCVIEN: UPDATE(MALOP) --> CHECK CONSTRAINT
--  GIANGDAY: UPDATE(DENNGAY)
--  KETQUATHI: INSERT, UPDATE(NGTHI)


-- GIANGDAY: UPDATE(DENNGAY)
CREATE TRIGGER NGTHI_DENNGAY_GIANGDAY_UPDATE_2
ON GIANGDAY
FOR INSERT
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN HOCVIEN AS HV ON HV.MALOP = inserted.MALOP
		JOIN KETQUATHI AS KQ ON KQ.MAHV = HV.MAHV AND inserted.MAMH = KQ.MAMH
		WHERE inserted.DENNGAY < KQ.NGTHI
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> UPDATE GIANGDAY(DENNGAY) KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> UPDATE GIANGDAY(DENNGAY) THANH CONG';
	END
END

DROP TRIGGER NGTHI_DENNGAY_GIANGDAY_UPDATE_2;

-- Test trigger

-- THANH CONG
UPDATE GIANGDAY
SET DENNGAY = '2006-05-10 00:00:00'
WHERE MALOP = 'K13' AND MAMH = 'CTRR';

-- KHONG THANH CONG
UPDATE GIANGDAY
SET DENNGAY = '2006-05-13 00:00:00'
WHERE MALOP = 'K13' AND MAMH = 'CTRR';


-- KETQUATHI: INSERT
CREATE TRIGGER NGTHI_DENNGAY_KETQUATHI_INSERT_2
ON KETQUATHI
FOR INSERT
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN GIANGDAY AS GD
		ON GD.MAMH = inserted.MAMH
		JOIN HOCVIEN AS HV
		ON HV.MAHV = inserted.MAHV AND HV.MALOP = GD.MALOP
		WHERE inserted.NGTHI > GD.DENNGAY
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> INSERT KETQUATHI KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> INSERT KETQUATHI THANH CONG';
	END
END

-- Test trigger

-- THANH CONG
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1303', 'CSDL', 2, '2006-12-25 00:00:00', 4);

-- WRONG
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM)
VALUES ('K1303', 'CSDL', 3, '2006-12-10 00:00:00', 4);

-- KETQUATHI: UPDATE(NGTHI)
CREATE TRIGGER NGTHI_DENNGAY_KETQUATHI_UPDATE_NGTHI
ON KETQUATHI
AFTER UPDATE
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN GIANGDAY AS GD
		ON GD.MAMH = inserted.MAMH
		JOIN HOCVIEN AS HV
		ON HV.MAHV = inserted.MAHV AND HV.MALOP = GD.MALOP
		WHERE inserted.NGTHI > GD.DENNGAY
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> UPDATE KETQUATHI(NGTHI) KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG --> UPDATE KETQUATHI(NGTHI) THANH CONG';
	END
END

-- Test Trigger

-- WRONG
UPDATE KETQUATHI
SET NGTHI = '2006-12-08 00:00:00'
WHERE MAHV = 'K1204' AND MAMH = 'CTDLGT' AND LANTHI = 1;

-- CORRECT
UPDATE KETQUATHI
SET NGTHI = '2006-12-30 00:00:00'
WHERE MAHV = 'K1204' AND MAMH = 'CTDLGT' AND LANTHI = 1;

-------------------------------- Cau 24 ---------------------------
-- Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách.

--  Bối cảnh: GIANGDAY, GIAOVIEN, MONHOC
--  GIAOVIEN: UPDATE(MAKHOA)
--  MONHOC: UPDATE(MAKHOA)
--  GIANGDAY: INSERT, UPDATE(MAGV)

-- GIAOVIEN: UPDATE(MAKHOA)
CREATE TRIGGER GIANGDAY_GIAOVIEN_UPDATE
ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN GIANGDAY AS GD
		ON inserted.MAGV = GD.MAGV
		JOIN MONHOC AS MH
		ON GD.MAMH = MH.MAMH
		WHERE MH.MAKHOA = inserted.MAKHOA
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> UPDATE GIAOVIEN(MAKHOA) KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> UPDATE GIAOVIEN(MAKHOA) THANH CONG';
	END
END

DROP TRIGGER GIANGDAY_GIAOVIEN_UPDATE;

-- Test trigger 

-- Wrong
UPDATE GIAOVIEN
SET MAKHOA = 'HTTT'
WHERE MAGV = 'GV08';

-- MONHOC: UPDATE(MAKHOA)
CREATE TRIGGER GIANGDAY_MONHOC_UPDATE
ON MONHOC
FOR UPDATE
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN GIANGDAY AS GD
		ON GD.MAMH = inserted.MAMH
		JOIN GIAOVIEN AS GV
		ON GD.MAGV = GV.MAGV
		WHERE GV.MAKHOA = inserted.MAKHOA
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> UPDATE MONHOC(MAKHOA) KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> UPDATE MONHOC(MAKHOA) THANH CONG';
	END
END

DROP TRIGGER GIANGDAY_MONHOC_UPDATE;

-- Test trigger
UPDATE MONHOC
SET MAKHOA = 'HTTT'
WHERE MAMH = 'CTDLGT';

-- GIANGDAY: INSERT
CREATE TRIGGER GIANGDAY_GD_INSERT
ON GIANGDAY
FOR INSERT
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN MONHOC AS MH
		ON MH.MAMH = inserted.MAMH
		JOIN GIAOVIEN AS GV
		ON inserted.MAGV = GV.MAGV
		WHERE GV.MAKHOA = MH.MAKHOA
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> INSERT GIANGDAY KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> INSERT GIANGDAY THANH CONG';
	END
END

DROP TRIGGER GIANGDAY_GD_INSERT;

-- Test trigger
INSERT INTO GIANGDAY (MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY)
VALUES ('K11', 'TKCSDL', 'GV10', 2, 2006, '2006-06-01 00:00:00', '2006-07-18 00:00:00');

DELETE FROM GIANGDAY
WHERE MALOP = 'K11' AND MAMH = 'TKCSDL' AND MAGV = 'GV05';

-- GIANGDAY: UPDATE(MAGV)
CREATE TRIGGER GIANGDAY_GD_UPDATE
ON GIANGDAY
FOR UPDATE
AS
BEGIN
	IF NOT EXISTS (
		SELECT *
		FROM inserted
		JOIN MONHOC AS MH
		ON MH.MAMH = inserted.MAMH
		JOIN GIAOVIEN AS GV
		ON inserted.MAGV = GV.MAGV
		WHERE GV.MAKHOA = MH.MAKHOA
	)
	BEGIN
		PRINT 'KHONG THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> INSERT GIANGDAY KHONG THANH CONG';
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		PRINT 'THOA DIEU KIEN: GIAO VIEN CHI DUOC PHAN CONG GIANG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH --> INSERT GIANGDAY THANH CONG';
	END
END

-- Test trigger

-- Wrong
UPDATE GIANGDAY
SET MAGV = 'GV01'
WHERE MALOP = 'K11' AND MAMH = 'CSDL';

------------------------------- Cau 23 -----------------------------
-- Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học (sau 
-- khi học xong những môn học phải học trước mới được học những môn liền sau). 

-- Bối cảnh: GIANGDAY, DIEUKIEN
-- GIANGDAY: INSERT, DELETE

-- GIANGDAY: INSERT
CREATE TRIGGER PHANCONG_GIANGDAY_INSERT
ON GIANGDAY
FOR INSERT
AS
BEGIN
    DECLARE @MALOP CHAR(3), @MAMH VARCHAR(10), @NAM SMALLINT, @HOCKY TINYINT

    -- Gán giá trị
    SELECT @MALOP = MALOP, @MAMH = MAMH, @NAM = NAM, @HOCKY = HOCKY
    FROM inserted

    -- Kiểm tra có môn học tiên quyết không
    IF EXISTS (
        SELECT *
        FROM DIEUKIEN DK
        WHERE DK.MAMH = @MAMH
    )
    BEGIN
        -- Tồn tại môn học tiên quyết --> kiểm tra xem các môn học tiên quyết đã được giảng dạy chưa
        IF NOT EXISTS (
            SELECT *
            FROM DIEUKIEN DK
            JOIN GIANGDAY GD ON GD.MAMH = DK.MAMH_TRUOC
            WHERE GD.MALOP = @MALOP AND DK.MAMH = @MAMH AND GD.NAM <= @NAM AND GD.HOCKY <= @HOCKY
        )
        BEGIN
            PRINT 'KHONG THOA DIEU KIEN: PHAN CONG GIANG DAY MOT MON HOC, PHAI XET DEN THU TU TRUOC SAU GIUA CAC MON --> INSERT KHONG THANH CONG'
            ROLLBACK TRANSACTION;
        END
        ELSE 
        BEGIN
            PRINT 'THOA DIEU KIEN: PHAN CONG GIANG DAY MOT MON HOC, PHAI XET DEN THU TU TRUOC SAU GIUA CAC MON --> INSERT THANH CONG'
        END
    END
END


DROP TRIGGER PHANCONG_GIANGDAY_INSERT;

-- GIANGDAY: DELETE 
CREATE TRIGGER PHANCONG_GIANGDAY_DELETE
ON GIANGDAY
FOR DELETE
AS 
BEGIN
    DECLARE @MALOP CHAR(3), @MAMH VARCHAR(10)

    -- Gán giá trị
    SELECT @MALOP = MALOP, @MAMH = MAMH
    FROM deleted

    -- Kiểm tra có môn học tiên quyết không
    IF EXISTS (
        SELECT *
        FROM DIEUKIEN DK
        WHERE DK.MAMH_TRUOC = @MAMH
    )
    BEGIN
        -- Tồn tại môn học tiên quyết --> kiểm tra xem các môn học tiên quyết đã được giảng dạy chưa
        IF EXISTS (
            SELECT *
            FROM DIEUKIEN DK
            JOIN GIANGDAY GD ON GD.MAMH = DK.MAMH
            WHERE GD.MALOP = @MALOP AND DK.MAMH_TRUOC = @MAMH
        )
        BEGIN
            PRINT 'KHONG THOA DIEU KIEN: MON HOC LA DIEU KIEN TIEN QUYET CUA MON KHAC --> DELETE KHONG THANH CONG'
            ROLLBACK TRANSACTION;
        END
        ELSE 
        BEGIN
            PRINT 'THOA DIEU KIEN: MON HOC KHONG PHAI LA DIEU KIEN TIEN QUYET CUA MON KHAC --> DELETE THANH CONG'
        END
    END
END

------------------------------ Cau 18 --------------------------
-- Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng 
-- một bộ không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và 
-- (“B”,”A”). 

-- Bối cảnh: DIEUKIEN
-- DIEUKIEN: INSERT
CREATE TRIGGER TRG_DIEUKIEN_INSERT
ON DIEUKIEN
FOR INSERT
AS
BEGIN
    DECLARE @MAMH VARCHAR(10), @MAMH_TRUOC VARCHAR(10);

    -- Gán giá trị từ bảng inserted
    SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC
    FROM inserted;

    -- Kiểm tra điều kiện MAMH và MAMH_TRUOC không giống nhau
    IF @MAMH = @MAMH_TRUOC
    BEGIN
        PRINT 'KHONG THOA DIEU KIEN: MAMH VA MAMH_TRUOC KHONG DUOC GIONG NHAU --> INSERT KHONG THANH CONG';
        ROLLBACK TRANSACTION;
        RETURN;
    END

    -- Kiểm tra điều kiện không tồn tại hai bộ hoán đổi cho nhau
    IF EXISTS (
        SELECT * 
        FROM DIEUKIEN 
        WHERE MAMH = @MAMH_TRUOC AND MAMH_TRUOC = @MAMH
    )
    BEGIN
        PRINT 'KHONG THOA DIEU KIEN: KHONG DUOC TON TAI HAI BO GIA TRI HOAN DOI NHAU --> INSERT KHONG THANH CONG';
        ROLLBACK TRANSACTION;
    END
END;


-- Test trigger

-- Thêm bộ dữ liệu không hợp lệ vào DIEUKIEN
INSERT INTO DIEUKIEN (MAMH, MAMH_TRUOC)
VALUES ('CSDL', 'CSDL');


INSERT INTO DIEUKIEN (MAMH, MAMH_TRUOC)
VALUES ('CTRR', 'CSDL');

-- Correct
INSERT INTO DIEUKIEN (MAMH, MAMH_TRUOC)
VALUES ('PTTKHTTT', 'THDC');